return {
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                    oo                                  oooooooooooooRooooooooo                              ",
    "                                 ooo  ooo                               X            r         oooo                          ",
    "          ooooooRoooooooooooooooo        ooooo                          X            r                                       ",
    "          X     r                            X                          X            r                                       ",
    "          X     r                            X                          X            r                    oo                 ",
    "          X     r                            X                          X                              ooo X                 ",
    "          X     r                            X                          X      oooooooooooooooooooooRoo    X                 ",
    "          X                                  X                                                      r      X                 ",
    "          X                                  X                                                      r      X                 ",
    "          X                                  X                                                      r      X                 ",
    "          X      oooooooooooRoooooooooooo                                                           r      X                 ",
    "                            r                                                                       r                        ",
    "                            r                    oooooooooooooooooooo   o                           r                        ",
    "                            r                                           X          ooRooooooooooo                            ",
    "                            r                X                          X            r                     X                 ",
    "r                           r                X                          X            r                     X                 ",
    "r                           r                X                          X            r                     X                 ",
    "r                                            X                          X            r                     X                 ",
    "r                       oooooooooooooooooooooX                          X            r                     X                 ",
    "r                                            X                          X            r                     X                 ",
    "                                             X                          X                                  X                 ",
    "                                                                        Xoooogooooooooooooooo   RooooooooooX                 ",
    "                                             X                          X                       r          X                 ",
    "                                             X                          X                       r          X                 ",
    "                                             X                          X                       r          X                 ",
    "           ooogooooooo   ooooooo  RooooooooooX                          X                                  X                 ",
    "          o                       r          X                          X    ooRooooo                      X                 ",
    "          X                       r          X                          X      r                           X                 ",
    "          X                       r          X                                 r                                             ",
    "          X                       r          X                                 r                                             ",
    "          X                       r          X                                 r                                             ",
    "          X                       r          X                                 r                                             ",
    "          X                       r          X                                                       oo                      ",
    "                                                                       ooooooooooooooooooooooogoooooo  oooooo                ",
    "                                       oo                   ooooooooRoo                                      ooooooooooooo   ",
    "         ooooooooooooRogooooooooooooooo  ooooooooooooooooooo       Xr X                                                   ooo",
    "ooooooooo         XXXrX                                            Xr X                                                      ",
    "                 X   rXXXX                                         Xr XXXXXXXXXXXXXXXXXXXXX                                  ",
    "              XXX    r    XXXXXXXXXXXXXXXX                         Xr                      XXX                               ",
    "             X       r                    X                        Xr                         X                              ",
    "             X       r                    X                        Xr                         X                              ",
    "             X       r                     XXXXXXXXXXXXXXXXXXXXXXXXXr                         X                              ",
    "             X       r                                              r                         X                              ",
    "             X       r                          ooooooooooooooooooooooooooo     oooooooo      X                              ",
    "              oooooooooooo                oooooo                           ooooo       X      X                              ",
    "                          ooooooRooooooooo                                             X       XX                            ",
    "                              X r X                                                    X         X                           ",
    "                              X r X                                                   X           X                          ",
    "                              X r X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX             XXXXXXXXXXXXX             ",
    "                             XX r XX                                                                            X            ",
    "                        XXXXX   r                                                                               X            ",
    "                    XXXX                                                                                        X            ",
    "                   X                                                                                            X            ",
    "                   X                                                                                             X           ",
    "                   X                                                                                             X           ",
    "                   X                                                                                             X           ",
    "          XXXXXXX  X                                                                                             X           ",
    "     XXXXX       XXX                          oooooooo oooooooRBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB                   X           ",
    "    X                                                         r                          XXXXXoooo               X           ",
    "    X                                                         r                                                  X           ",
    "    X            XXX                                          r                                                   XXX        ",
    "     XXXX      XX  X                                          r                                                      XXXXX   ",
    "         XXXXXX    X                                          r                                                           X  ",
    "                   X                                          r                                                           X  ",
    "                   X                                          r                                                           X  ",
    "                   X                                                                                                      X  ",
    "                   X                oooooooooooooRoooooooooooooooooo oooo oooo oooooooooooRo                              X  ",
    "                   X                             r                                        r                               X  ",
    "                 XX                              r                                        r                               X  ",
    "                X                                r                                        r                               X  ",
    "                X                                r                                        r                               X  ",
    "                X                                r                                        r                         oooooo   ",
    "                X                                r                                                             ooooo         ",
    "                X                                                                 oooooooooooooooooogoooooooooo              ",
    "                 ooooooooRooooogooooooooooooooooooooooooooooo           ooooooRooo                                           ",
    "                        Xr X                              XXX  ooooooooo     Xr X                                            ",
    "                        Xr X                  XXXXXXXXXXXXX    XXXXXXXXXXXX  Xr X                                            ",
    "                        Xr X                 X                             X Xr X                        XXX                 ",
    "              XXXXXXXXXXXr XXXXXXXXXXXXXXXXXX                               XXr XX                XXXXXXX   XXXXXXX          ",
    "           XXX           r                                                    r   X           XXXX                 XXXX      ",
    "         X               r                                                    r   X        XXX                         XXX   ",
    "         X               r                                                    r    XX    XX                               XX ",
    "         X               r                                                    r      XXXX                                   X",
    "         X               r                   ooooooooooooRoooooooooooooooo    r                                             X",
    "          ooooooRo       r                               r                    r                                             X",
    "             X  r        r                               r                    r                ooooooooRoooooooo            X",
    "             X  r                                        r                    r                        r                    X",
    "             X             ooo                           r                    r                        r                    X",
    "              ooooooooooooo   ooooooooooooo              r                    r                        r                    X",
    "                                           oo                                 r                        r                    X",
    "                                             BBBBBBBBBBBBBBBBBBBBBBBBBBBBB    r                                             X",
    "                                                                          oo                                                X",
    "                                                                            oooo                                    oooooooo ",
    "                                                                                BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB         ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
}