return {
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                 BBBBBBBBBBBBBBBBBBBBBBB                                                                                     ",
    "             oooo                      X                                                                                     ",
    "             X                         X                                         oooo                                        ",
    "             X                        X                                 oooo o o                                             ",
    "              XXXXXXXXXXXXXXXXXXXXXXXX               oooRooooooooooooooo                                                     ",
    "                                                        r                                                                    ",
    "                                                        r                                                                    ",
    "                                                        r                                                                    ",
    "                                                        r                                                                    ",
    "                                                        r                                                                    ",
    "                                                                                                                             ",
    "                                              ooooooooooooooRoo                                                              ",
    "                                                            r                                 oo                             ",
    "                      ooooooooRo                            r                                    oo          oooooRo         ",
    "                oooooo        C                             r                                       oo oooooo     r          ",
    "              oo            XXr                             r                                                     r          ",
    "             o           XXX  r                                                                                   r          ",
    "      oooogoo        XXXX     r                                                                                   r          ",
    "  oooo              X                                            ooo                                              r          ",
    "oo                 X                              ooooooooooooooo   ooooooooo  oo  oooooooo                       r         o",
    "                   X                                                                                                   ooooo ",
    "                   X                                                                                             oooooo      ",
    "                   X                                                                                             X           ",
    "                   X                                                                                             X           ",
    "                   X                                                                                             X           ",
    "                  X                                                                                              X           ",
    "      XXXXXXXXXXXX                                                                                               X           ",
    "     X                                                                                                           X           ",
    "     X                                                                                                            X          ",
    "     X                                                                   ooooooooooooooooo                         XXX       ",
    "     X                                                                    X               oogooooo  oooooooo          X      ",
    "     X                                  oooooRooooooooooo                  XXXXXXXXXX           X           ooRo      X      ",
    "    X                    oooo                r                                       XXXXXXXXXXX              r       X      ",
    "    X                 ooo   X                r                                          r                     r       X      ",
    "    X             oooo     X                 r                                          r                     r       X      ",
    "    X        oRooo      XXX                  r                                          r                     r       X      ",
    "    X         C     XXXX                     r                            ooooooooooooo r                     r       X      ",
    "    X         rXXXXX                         r                                          r                     r       X      ",
    "    X         r                                                                         r                        ooooo       ",
    "    X         r                  oooooooooooooo                                         r                 ooooooo            ",
    "    X         r               XGX                                                                     oooo                   ",
    "    X         r                                                                       oooooooooooooooo                       ",
    "    X         r                                                                       X                                      ",
    "    X         r                                                                       X                                      ",
    "    XoooRo    r                                                                        X                                     ",
    "    X   r     r                                                                         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    ",
    "    X   r     r                                        ooRooooooo                               r  r  r  r               X   ",
    "    X   r     r                                          r                                      r  r  r  r                X  ",
    "    X   r     r                                          r                                      r  r  r  r                X  ",
    "    X   r     r                                          r                                      r  r  r  r                X  ",
    "    X                                                    r                                      r     r  r                X  ",
    "     BBBBBBBBBBBBBBBB                                    r                                      r        r                X  ",
    "                    X                        oooooooo                                                    r                X  ",
    "                    X                         X      oooooo                                              r                X  ",
    "                    X                          X           oo                                            r                X  ",
    "                    X                           X            oRooooooooo                                 r                X  ",
    "                    X                           X             C        X                                                  X  ",
    "                    X                 Roooo      XX           C        X                               ooooooooo          X  ",
    "       XXXX         X                 rX   o       XXXX       C      XX     oooooooRoooooooooo          X       ooo       X  ",
    "      X    X        X                 rX    o          XXXXXXXCXXXXXX              r                     XXXX      ooooooo   ",
    "      X    X        X                 rX     oo               r                    r                         X               ",
    "      X     XXX     X                 rX      X               r                    r                          X              ",
    "      X        XXXXXX                 rX      X               r                    r                          X              ",
    "      X                                 X      ooooooo        r                    r                           XXXXXXXX      ",
    "      X        XXXXXX        ooRooooo    X     X   X  oo      r                    r                                   X     ",
    "       XXXXXXXXX    X          r          XXXX X   X    ooo   r                                                        X     ",
    "                    X          r              XX    X     X   r       oooo       ooooooo                               X     ",
    "                   X           r                     XX   X        ooo  X               ooo                            X     ",
    "                  X            r                       X   oooooooo    X                                  oooRooooooo  X     ",
    "                  X            r                        X              X                                     r         X     ",
    "                 X                                       X           XX                                      r         X     ",
    "    XXXXXXXXXXXXX            ooooooooooRooooo            X      XXXXX                                        r         X     ",
    "   X                                   r                  X    X                                    oooo               X     ",
    "   X                                   r                  X    X                                     X  ooooooooooooooo      ",
    "   X                                   r                  X    X                                      XX                     ",
    "   X                                   r                  X    X                                        XXXXXXXXXXXXX        ",
    "   X                                   r                  X     oooooo                                               X       ",
    "    oooooo                                                X           oo           oooo                               X      ",
    "          o                     oooooooooooooooooooooooooo              ooooooooooo    ooooooooogoo                    X     ",
    "           ooooooooooooooooooooo                                                                   ooooooooooooooo     X     ",
    "                                                                                                                 X     X     ",
}