return {
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                        XXCXX                                                ",
    "                                                                        X r X                                                ",
    "                                                                        X r X                                                ",
    "                                                                        X r                                                  ",
    "                                                                        X r    XX                                            ",
    "                                                                          r XXX                                              ",
    "                                                                   XXXX   r X                                                ",
    "                                                                       XX r X                                                ",
    "                                                                        X r X                                                ",
    "                                                                        X r X                                                ",
    "                                                                        X r X                                                ",
    "                                                                        X r X                                                ",
    "                                                                        X r X                                                ",
    "                                                                        X r X                                                ",
    "                                                                        X r X                                                ",
    "                                                                        X r X                                                ",
    "                                                                       X  r  X                                               ",
    "                                                                       X  r  X                                               ",
    "                                                                          r                                                  ",
    "                                                                                                                             ",
    "                                                                oooooooooooooooooooo                                         ",
    "                                                          oooooo                    ooo                                      ",
    "                                                       ooo                             oo                                    ",
    "                                                   oRoo                                  o                                   ",
    "                                                  o r X                                   oo                                 ",
    "                                                 oX r X                                     o                                ",
    "                                                o X r  X                                     o   ooooooRooo                  ",
    "                                               o  X r  X                                      o        r                     ",
    "                                              o   X r  X                                       o       r                     ",
    "                                              X  X  r  X                                       X       r                     ",
    "                                             o   X  r   X                                       o      r                     ",
    "                                            o    X  r   X                                       X      r                     ",
    "                                            X    X  r    X                                       o                           ",
    "                                           o     X  r    X                                        o    ooooooRoo             ",
    "                                          oX    X   r    X                                        X          r               ",
    "                                            XXXX    r    X                                         o         r               ",
    "                                                    r    X                                         X         r               ",
    "                                                    r    X                                          o        r               ",
    "                          ooooRoooooo oooo          r    X                                          X        r               ",
    "                              r          Xooo         ooo                                            o                       ",
    "                              r         X    ooooooooo                                               X                       ",
    "    oooooooooooooooo          r         X                                                             o                      ",
    "    X              X          r        X                                                               oo                    ",
    "    X              X          r       X                                                                  o                   ",
    "    X                         r       X                        XXXXXXXXXXXXXXXXXXXXXXXXX                  o                  ",
    "    X                                X           XXXXXXXXXXXXXX                         XX                 o                 ",
    "    X                 oRoooooooooo   X        XXX                                         XX               X                 ",
    "                   oo  r            X        X                                              X               o                ",
    "    oooo        oo X   r           X        X                                                XX              og              ",
    "    X    ooooRo    X   r           X       X                                                   XXX             o             ",
    "    X        r     X   r          X       X                                                       XXXXX         o            ",
    "    X        r     X             X       X                                                             XXXXX     o           ",
    "    X        r     X  oo ooo oR  X      X                            Roooooooooooooo                        XXXXXXooR        ",
    "    X              X          r X       X                            C             X                                r        ",
    "    X   ooRooooo   X          r X      X                             rXXXXXXXXXXXXX                                 r        ",
    "    X     r        X           o       X                             r                                              r        ",
    "    X     r        X         oo        X                             r                                              r        ",
    "   X      r         X       o         X                              r                                                       ",
    "          r               oo          X                                                                           oooooo     ",
    "                        oo           X        oooRoooooooooooooooooooooooo                                     ooo      oo   ",
    "oooooooooooooooooooooooo             X        X  C                       X                    ooooooooooooooooo           ooo",
    "                                     X         XXCXXXXXXXXXXXXXXXXXXXXXXX                 oooo                               ",
    "                                     X           r                                    oooo                                   ",
    "                                     X           r                                 ooo                                       ",
    "                                     X           r                              ooo                                          ",
    "                                     X           r                            oo                                             ",
    "                                     X           r                        oooo                                               ",
    "                                     X                     ooooooooooooooo                                                   ",
    "                                     X         oooooooooooo                                                                  ",
    "                                    X         o                                                                              ",
    "                                    X        o                                                                               ",
    "                                    X       o                                                                                ",
    "                                   X        X                                                                                ",
    "                                   X        X                                                                                ",
    "                                   X        X                                                                                ",
    "                                  X         X                                                                                ",
    "                                  X          XXXXXX                                                                          ",
    "                                XXX                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                 ",
    "                               X                                                            XXXXXX                           ",
    "                        XXXXXXX                                                                   XXX                        ",
    "                  XXXXXX                                                                             XXXX                    ",
    "               XXX                                                                                       XX                  ",
    "             XX                                                                                            XX                ",
    "           XX                                     oooRoooo                                                   X               ",
    "          X                         oooogooooooooo   r     ooo ooo ooooooooooooRooo oooooooo                  X              ",
    "         X                          X           X    r                         r            oo                X              ",
    "        X                            XXXXXXXXXXX     r                         r                               X             ",
    "        X                                            r                         r                                X            ",
    "        X                                            r                         r                                 X           ",
    "        X                                            r                         r                                 X           ",
    "        X                                            r                                                            X          ",
    "        X   oooooRoo           oooo                    oooooooooooooooooooooooooooooooooooooooooo                 X          ",
    "        X        r           oo    oooo          oooooo                                          oooo             X     XX   ",
    "        X        r          o          oooooooooo                                                    oooR          X   X  X  ",
    "        X        r     ooooo                                                                         X  r          X  X    X ",
    "        X        r     X                                                                             X  r          X  X    X ",
    "        X        r     X                                                                          XXXX  r          X  X    X ",
    "        XoooRoo        XX                                                                     XXXX      r          X  XXXCX X",
    "        X   r  ooo      XXX                                                        XXXXXXXXXXX          r          X  X  r  X",
    "        X   r             XXXXXXXXXXXXX                                   XXXXXXXXX                     r          X  X  r  X",
    "        X   r                          XXXXXXXX                      XXXXX                              r           XX   r  X",
    "        X   r                                  XX                  XX                                   r                r  X",
    "        X   r                                    XX              XX                                                      r  X",
    "        X                                          X            X                             oooooooooooooooo     XXXX    X ",
    "        X   ooooooooo                               X           X                            o               X      X  XXXX  ",
    "        X   X       X                               X          X          Roooooooooooooooooo     XXXXXXXXXXX       X        ",
    "        X    XXXXXXX       ooooRooooooooooooRoo      X         X          C                      X                  X        ",
    "        X                      r            r         XXXXXXXXX           rXXXXXXXXXXXXXXXXXXXXXX                   X        ",
    "        X                      r            r                             r                    r                    X        ",
    "        X                      r            r                             r                    r                    X        ",
    "        X                      r            r        oooooooooo           r                    r                    X        ",
    "         ooooooooo             r            r        X        X           r                    r                    X        ",
    "                  oo           r            r        X        X           r                    r                  oo         ",
    "                    oo                               X         o          r                    r          ooooogoo           ",
    "                      BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB           oo                             r                  X          ",
    "                                                                  oooooooooooooooooooooooooooo r                  X          ",
    "                                                                                             X r                  X          ",
    "                                                                                             X r                  X          ",
    "                                                                                             X                    X          ",
    "                                                                                              ooooo               X          ",
    "                                                                                                 X                X          ",
    "                                                                                             XXXX                 X          ",
}