return {
    "                                                                                                                 X     X     ",
    "                                                                                                                 X     X     ",
    "                                                                                                                 X     X     ",
    "                                                                                                                 X     X     ",
    "                                                                                                                 X     X     ",
    "                                                                                                                 X     X     ",
    "                                                                                                                 X     X     ",
    "     XXXXX                                                                                                       X     X     ",
    "   XX     XXX        XXXXXXXXXXXXXXXXXXXXX                                                                       X     X     ",
    "  X          XXXXXXXX                   r XXXXXXXXX                                                              X     X     ",
    "  X           r                         r   r      XXXXX           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX             X     X     ",
    "  X           r                         r   r           XXXXXXXXXXX                                 XXXX         X     X     ",
    "   X          r                         r   r                                                           X        X      X    ",
    "    XXXXXXX   r                         r   r                                                            X       X      X    ",
    "           X  r                             r                                                            X      X       X    ",
    "            X r                             r                                                             X     X        X   ",
    "            X r              oooooooooooo   r                                                              X    X        X   ",
    "            X r               XXXXXXXXXX                                                                   X   X         X   ",
    "           Xr r                             ooooooooo                        oRooooooooo oo oo oo oRooo     XXX           X  ",
    "           Xr r                              XXXXXXXXoooooooooooo             r                    r                      X  ",
    "           Xr                                        XXXXXXXXXXX              r                    r                      X  ",
    "          X r                                                                 r                    r                      X  ",
    "          X r                                                                 r                    r                      X  ",
    "        XX  r                                                                 r                    r                      X  ",
    "     XXX    r                                                                                                 XXX         X  ",
    "    X       r                     oooooooooooo                         ooooooooooooRoo       oooooooooo       X  X      XX   ",
    "   X        r                      X        X                                      r                          X   XXXXXX     ",
    "   X        r                       XXXXXXXX                                       r                           X             ",
    "   X                                                                               r                            XX           ",
    "   X                                                                               r                              X          ",
    "   XooRoooooooooooooo                                 oooooooo                                                     XX        ",
    "   X  r                                                XXXXXX                                                        XX      ",
    "  X   r                                                                                                                X     ",
    "  X   r                                                                                                                X     ",
    "  X   r                                                                                                                 X    ",
    "  X   r                                    oooooooooooo                                                                 X    ",
    "  X                              ooooooooo  X        X                                                                  X    ",
    "  X oooo Ro oo  oooooo      ooooo       X    XXXXXXXX                                                oooooooooo          X   ",
    "  X      r                   X   XXXXXXX                                                            o        X           X   ",
    " X       r                    XXX                                                            ooooooo         X           X   ",
    " X       r                                                   ooooooR              ooogooooooo               X            X   ",
    " X       r                                                    XXXXXr               X                     XXX             X   ",
    " X                                                                 r                X                   X                 XXX",
    " Xoooooooo                              ooooooooo                  r                 XXXX            XXX                     ",
    " X                                       XXXXXXX                   r                     X          X                        ",
    " X                                                                 r                      XXX      X                         ",
    " X                                                                 r                         X     X                         ",
    " X                                                                 r                         X    X                          ",
    " X                                  oooooooooooooooooooooo                                   X    X                          ",
    " X                    ogoooooooooooo                      oooooooooooooooooo                 X    X                          ",
    " X                     X                                                    oooooooR         X    X               Roooooooooo",
    " X                      X                                                         Xr         X    X               C          ",
    "  oo                    X                                                         Xr         X    X               rXXXXXXX   ",
    "    oooR                 XX                        XXXXXXX                        X          X    X               r       X  ",
    "    XXXr                   X                   XXXX       XXX                     Xooooooo   X    X               r       X  ",
    "   X   r                   X                  X              XXXXXXX             X           X    X               r       X  ",
    "  X    r                   X                  X                     XXXXXXXXXXXXX            X    X                       X  ",
    "  X    r                   X                 X                                r              X    X                        X ",
    "  X    r                    X               X                                 r              X    Xooooooooooo             X ",
    "  X    r                    X               X                                 r              X   X           X             X ",
    "  X                         X               X      oooooooo                   r              X   X           X             X ",
    "  XoRoooo                    XXXXXXXX        oooRoo      X                    r              X   X           X             X ",
    "  X r                                XXXX       C        X          ooooooooo r              X   X           X             X ",
    "  X r                                    XX     C     XXX           X     XX  r              X   X                         X ",
    "  X r                                      X    C   XX               X   X    r              X   X                         X ",
    "  X r                                       X   C  X                 X   X    r           oog    X                         X ",
    "  X                                         X   C  X                  X  X               o       X           ooogooooooRooo  ",
    "   oooooo                                    XXXCXX                   X   ooooooooooooooo       X         oo           r  X  ",
    "         BBBBBBBBBBBBBBBBBBR                    r                     X                         X   oRooo              r  X  ",
    "                          Xr                    r                     X                        X     r                 r  X  ",
    "                 XXXXXXXXX r                    r                      X                       X     r                    X  ",
    "                X          r                                           X                       X     r                    X  ",
    "       XXXXXXXXX           r                XXXXXXXXC                   XXX                    X     r                    X  ",
    "      X                    r                X       C                      X                   X     r                    X  ",
    "      X                    r                 X     Xr                       XXXXXXXX           X                          X  ",
    "     X                     r                  X    Xr                               XXXXX      XooooooooooRooo    ooooooooX  ",
    "     X                     r                  X    Xr                                    XXXXXX  X        r  X            X  ",
    "     X                     r                  X   X r                                            X        r  X            X  ",
    "     X                     r                  X   X r                                            X        r               X  ",
    "     X                     r                  X   X r                                            X        r               X  ",
    "      ooooooRoo            r      oooooooooooo    X                                              X        r               X  ",
    "      XXXXXXCX             r       X               ooooo                oooRoooooo               X        r               X  ",
    "     X      r              r        XXX                X                   r                              r               X  ",
    "     X      r              r           X             XX                    r                              r               X  ",
    "     X      r                          X            X                      r                                              X  ",
    "     X      r    ooooooooooo            X          X                       r                     ooooooooooooooogooooooooo   ",
    "     X      r     XXXXXXXXX             X          X                       r               oooooo                            ",
    "     X      r                            X         X                                       X                                 ",
    "     X      r                            X         X             ogooooRooooo               X                                ",
    "     X      r                            X         X                   r                    X                                ",
    "     X      r                            X         X                   r                    X                                ",
    "     X      r                            X         X                   r       ooooo        X                                ",
    "     X                                   X         X                   r       X   X        X                                ",
    "      oooooooooo                         X         X                   r       X   X        X                                ",
    "                oooooooooooooo            X        X                           X   X        X                                ",
    "                  XXXXXXXXXXX              X        oooooooooooooooooooo       X   X        X                                ",
    "                 X                         X                            ooooooo     ogoooooo                                 ",
    "                X                          X                                                                                 ",
    "                X                           X                                                                                ",
    "                X                           X                                                                                ",
    "                X                       ooooX                                                                                ",
    "                X                 ooooooXXXXX      XXXXXXXXXXXXXXXXXXXXXX                                                    ",
    "                X                  XXXXX    X     X                      XXXXXX                                              ",
    "                X                           X     X                            XXXXXXXXXXXXXXXXXXXXX                         ",
    "                X                            XXXXX                                                  XXXXXXXXX                ",
    "                X                                                                                            XX              ",
    "                 ooooR                                                                                         X             ",
    "                 XXXXr                                                                                         X             ",
    "                X    r                                                                                         X             ",
    "                X    r                                                                                         X             ",
    "                X    r                                                                                         X             ",
    "                X    r                                                                                         X             ",
    "                X           ooogooooooooooooooooo                                                              X             ",
    "                 ooooooooooo                     oooooooooooooooo ooooooooooooo                                X             ",
    "                                                                X               ooo                            X             ",
    "                                                                X                   ooo                        X             ",
    "                                                              XX                        ooR            oooooRoo              ",
    "                                                        XXXXXX                            r                 r  X             ",
    "                                                 XXXXXXX                                  r                 r  X             ",
    "                                           XXXXXX                                         r                 r  X             ",
    "                                          X                                               r                 r  X             ",
    "                                         X                                                r                 r  X             ",
    "                                         X                                                                     X             ",
    "                                         X                                         oooooooooooooooooooooooooooo              ",
    "                                         X                                oooooooo                             X             ",
    "XXX                                      X                                                                     X             ",
    "   X                                     X                                                                     X             ",
    "    XX                                   X                                                                     X             ",
    "      X                                  X                                                                     X             ",
    "       X                                 X                                                                     X             ",
    "        XXXXX                            X                                                                     X             ",
    "             X                         XXXooooooRo                                                             X             ",
    "             X                       XX         r                                             BBBBBBBBBBBBBBBBB              ",
    "ooo          X                      X           r                               ooooooRooooooo                               ",
    "   ooo       X                      X           r                                     r       X                              ",
    "     XoooRooo X                 XXXX            r                                     r       XXXXXX                         ",
    "   XX    r    X           XXXXXX                r                                     r             XXXX                     ",
    "  X      r    X  XXXXXXXXX                      r                                     r                 XXXXXXX              ",
    "  X      r     XX                               r                                     r                        XX            ",
    "  X      r                                      r                                     r                          X           ",
    "  X                                             r                                     r                           X          ",
    "  X                                             r                                     r                           X          ",
    "  X                                                                                                               X          ",
    "  X                                           ooooooooo  oooooooooooooogooo ooooo ooooo                           X          ",
    "  X                                     ooooo  X     X                                                            X          ",
    "  X                               oooo   X X   X     X                                                             X         ",
    "  X                         Rooo   XX    X X   X     X                                                             X         ",
    "  X                         rXX    XX    X X   X     X                                                             X         ",
    "  X                         rXX    XX    X X   X     X                                                             X         ",
    "  X                         rXX    XX    X X   X     X                                                             X         ",
    "  X                         rXX    XX    X X   X     X                                                             X         ",
    "  X                         rXX    XX    X X   X     X                                                             X         ",
    "  X                         rXX    XX    XXX   XXXXXXX                                                             X         ",
    "  X                         r                                                                                      X         ",
    "   oooooogo                  oo    oo    ooo                                                                       X         ",
    "           oooooooooooooooooo  oooo  oooo   oooooooooooooo                                                         X         ",
    "                                                         X                                                         X         ",
    "                                                         X                                                         X         ",
    "                                                        X                       ooRooooooooooR                     X         ",
    "                                                 XXXXXXX                          r          r                      X        ",
    "                                               XX                                 r          r                      X        ",
    "                                    XXXXXXXXXXX                                   r          r                      X        ",
    "                                   X                                              r          r                      X        ",
    "                 XXXXXXXXXXXXXXXXXX                                               r                                 X        ",
    "                X                                                                 r        oooooooRoo               X        ",
    "         XXXXXXX                                                                                  r                 X        ",
    "        X                                                            oooooooooooooooo             r                 X        ",
    "       X                                                                                          r                 X        ",
    "       X                                                                                          r                 X        ",
    "      X                                                                                           r                 X        ",
    "      X                                                                                                             X        ",
    "      X                                                   XGX                                 ooooooooooooo         X        ",
    "      X                                         ooooooooooXXX                                               oooooooo         ",
    "      X                           oooooooooooooo                                                            X                ",
    "      X               oooooooooooo             X                                                            X                ",
    "      X    ooooooooooo                         X                                                            X                ",
    "      X    X                                 XX                                                             X                ",
    "      X    X              XXXXXXXXXXXXXXXXXXX                                                               X                ",
    "      X     XXXXXXXXXXXXXX                                                                                  X                ",
    "      X                                                                                                      X               ",
    "      X                                                       ooRoooooooooooooooooooooRo                     X               ",
    "      X                                                         r                     r                       XXXXXX         ",
    "      X                                                         r                     r                             XXXX     ",
    "      X                                                         r                     r                                 XXXXX",
    "      X                                                         r                     r                                      ",
    "      X          ooo ooo oRoooooo                               r                     r                                      ",
    "      X                   r                                     r                     r                                      ",
    "      X                   r                                                                                                  ",
    "      X                   r                                   ooooo              Rooooooooooooooooooooo                      ",
    "      X                   r                            ooooooo  XXX              rX                    oooo                  ",
    "      X                   r                    oooooooo   XXXXXX                 rX                        ooo               ",
    "      X                               ooooooooo     XXXXXX                       rX                           oo             ",
    "       oogBBBBBBBBBBBBBBBBBBBBBBBBBBBB        XXXXXX                              X                             oo           ",
    "                                       XXXXXXX                             ooooooo                   XXXX         ooooooooooo",
    "                                 XXXXXX                             ooooooo                    XXXXXX    X                   ",
    "                           XXXXXX                                   X                    XXXXXX           X                  ",
    "                     XXXXXX                                         X              XXXXXX                 X                  ",
    "                 XXXX                                            oooX        XXXXXX                       X                  ",
    "                X                                            oRoo    X    XXX                             X                  ",
    "                X                                    oooo     r      X   X                                X                  ",
    "                X                               oRooo         r      X   X                                X                  ",
    "                X  XXXX                          r            r      X   X                                 X                 ",
    "                 XX                              r            r  oooo    X                                 X                 ",
    "                 X          ooooRo               r         oooooo        X                    oooooo       X                 ",
    "                 X     ooooo    r                r   oooooo               X             oooooo             X                 ",
    "                 X              r              oooooo                     X       oooooo                   X                 ",
    "                 X              r        oooooo                           Xooooooo                         X                 ",
    "                 X              r oooooRo X                            XX X                                 X                ",
    "                  X         oooooo  X  r  X                      XXXXXX  X                                  X                ",
    "                  X   oooooo        X  r  X                XXXXXX                                           X                ",
    "                   ooo              X  r  X          XXXXXX                                                 X                ",
    "                                    X  r  X    XXX XX                                                       X                ",
    "                XXXXXXXX            X  r  XXXXX   X                                                   ogooooX                ",
    "           XXXXX        X          XX  r                                                          oooo       X               ",
    "          X              X   XXXXXX    r                                 X    ooooRo                         X               ",
    "         X                XXX                                           o oooo    r                          X               ",
    "      XXX                              r                          oooooo    X     r                          X               ",
    "     X                                 r                    oooooo          X     r                          X               ",
    "    X                                  r          X   oooooo                X     r                          X               ",
    "    X          oooRoo                  r        oo ooo                      X                                X               ",
    "    X     ooooo   r                       oooooo                            X     r                    oooooo                ",
    "    X             r                 oooooR  X                               X     r              oooooo                      ",
    "     X            r          ooooooo  X  r  X                     XXXXXXX    X    r        ooooog                            ",
    "     X            r       ooo         X  r  X               XXXXXX       X   X       oooooo                                  ",
    "     X                 ooo            X  r  X         XXXXXX             X    ooooooo                                        ",
    "      o          oooooo                X r   X  XXXXXX                   X                                                   ",
    "       oooooooooo                      X r   XXX                         X                                                   ",
    "                                    XXXX                                 X                                                   ",
    "                              XXXXXX     r                               X                                                   ",
    "                        XXXXXX           r                        ooooooo X                                                  ",
    "                      XX                 r                  ooooRo        X                                                  ",
    "                     X                   r            oooooo    r         X                                                  ",
    "                     X                                          r         X                                                  ",
    "                      X                   oooooo                r         X                                                  ",
    "                      X             oooooo                      r         X                                                  ",
    "                      X       ooooRo                               ooooooo                                                   ",
    "                      Xooooooo    r                          oooooo                                                          ",
    "                      X           r                    oooooo                                                                ",
    "                      X           r              oooooo                                                                      ",
    "                       X          r        oooooo                                                                            ",
    "                       X             oooooo                                                                                  ",
    "                       X       oooooo                                                                                        ",
    "                        ooooooo                                                                                              ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
    "                                                                                                                             ",
}